name: Deploy project to VPS
on: [workflow_dispatch]
#on: push

jobs:
  # This workflow contains a single job called "build"
  connect_on_vps:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase : ${{ secrets.PASSPHRASE }}
          script: |
            mkdir testDir
            
